version: '3.8'

services:
    elasticsearch:
        image: elasticsearch:8.15.1
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - xpack.security.enabled=true
            - xpack.security.transport.ssl.enabled=true
            - xpack.security.transport.ssl.verification_mode=certificate
            - xpack.security.transport.ssl.keystore.path=certs/elastic-certificates.p12
            - xpack.security.transport.ssl.truststore.path=certs/elastic-certificates.p12
        volumes:
            - /data/elasticsearch/config:/usr/share/elasticsearch/config
            - /data/elasticsearch/data:/usr/share/elasticsearch/data
            - /data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
            - /data/elasticsearch/logs:/usr/share/elasticsearch/logs
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elk

    kibana:
        image: kibana:8.15.1
        container_name: kibana
        environment:
            - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=您的_elastic_用户密码
            - I18N_LOCALE=zh-CN
            - SERVER_NAME=kibana
            - SERVER_HOST=0.0.0.0
        volumes:
            - /data/kibana/config:/usr/share/kibana/config
            - /data/kibana/data:/usr/share/kibana/data
            - /data/kibana/plugins:/usr/share/kibana/plugins
            - /data/kibana/logs:/usr/share/kibana/logs
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        networks:
            - elk

    logstash:
        image: logstash:8.15.1
        container_name: logstash
        environment:
            - LS_JAVA_OPTS=-Xms1g -Xmx1g
        volumes:
            - /data/logstash/config:/usr/share/logstash/config
            - /data/logstash/pipeline:/usr/share/logstash/pipeline
        ports:
            - 5044:5044
            - 9600:9600
        depends_on:
            - elasticsearch
        networks:
            - elk

    filebeat:
        image: elastic/filebeat:8.15.1
        container_name: filebeat
        volumes:
            - /data/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - /data/logs:/usr/share/filebeat/logs
            - /data/filebeat/data:/usr/share/filebeat/data
            - /data/filebeat/logs:/usr/share/filebeat/logs
        command: ['filebeat', '-e', '-c', '/usr/share/filebeat/filebeat.yml']
        depends_on:
            - logstash
        networks:
            - elk

networks:
    elk:
        driver: bridge
