version: '3.8'

services:
    elasticsearch:
        image: elasticsearch:8.15.1
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - LANG=C.UTF-8
            - LC_ALL=C.UTF-8
        volumes:
            - /data/elasticsearch/config:/usr/share/elasticsearch/config
            - /data/elasticsearch/data:/usr/share/elasticsearch/data
            - /data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
            - /data/elasticsearch/logs:/usr/share/elasticsearch/logs
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elastic

    kibana:
        image: kibana:8.15.1
        container_name: kibana
        restart: always
        tty: true
        stdin_open: true
        logging:
            driver: 'json-file'
            options:
                max-size: '100m'
                max-file: '2'
        ports:
            - '5601:5601'
        networks:
            - elastic
        depends_on:
            - elasticsearch
        volumes:
            - /data/kibana/config:/usr/share/kibana/config
            - /data/kibana/data:/usr/share/kibana/data
            - /data/kibana/plugins:/usr/share/kibana/plugins
            - /data/kibana/logs:/usr/share/kibana/logs

    logstash:
        image: logstash:8.15.1
        container_name: logstash
        volumes:
            - /data/logstash/config:/usr/share/logstash/config
            - /data/logstash/pipeline:/usr/share/logstash/pipeline
        ports:
            - 5044:5044
            - 9600:9600
        depends_on:
            - elasticsearch
        networks:
            - elastic

    filebeat:
        image: elastic/filebeat:8.15.1
        container_name: filebeat
        restart: always
        tty: true
        stdin_open: true
        network_mode: host
        volumes:
            - /data/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - /data/logs:/usr/share/filebeat/target
            - /data/filebeat/data:/usr/share/filebeat/data
            - /data/filebeat/logs:/usr/share/filebeat/logs
        command: ['filebeat', '-e', '-c', '/usr/share/filebeat/filebeat.yml']
        depends_on:
            - logstash

networks:
    elastic:
        driver: bridge
