global:
    scrape_interval: 15s # 抓取数据的频率
    evaluation_interval: 15s # 评估告警规则的频率

scrape_configs:
    - job_name: 'consul-services'
      consul_sd_configs:
          - server: '192.168.0.214:8500' # 替换为你的 Consul 服务器地址
            token: 'w0AUQMc20dxNBF' # 替换为你的 Consul Token

      # relabel_configs 用于过滤和重命名服务
      relabel_configs:
          # 过滤掉 Consul 自己的节点
          - source_labels: ['__meta_consul_service']
            regex: '^consul$' # 匹配服务名称为 "consul" 的服务
            action: drop # 忽略这些服务

          # 保留其他服务
          - source_labels: ['__meta_consul_service']
            target_label: 'job' # 将服务名称分配到 Prometheus 的 'job' 标签

      metric_relabel_configs:
          - source_labels: ['__meta_consul_service']
            target_label: 'service' # 可选，将服务名称分配到 'service' 标签
    - job_name: 'node_exporter'
      static_configs:
        - targets: ['192.168.0.253:9100']

