version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx:stable
    network_mode: host
    # ports:
    #   - 80:80
    #   - 443:443
    volumes:
      - /home/docker/nginx/conf.d:/etc/nginx/conf.d
      - /home/docker/nginx/ssl:/etc/nginx/ssl
      - /home/docker/nginx/dist:/usr/share/nginx/html
      - /home/docker/nginx/logs:/var/log/nginx
      - /home/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
